### ISSUE TITLE
2 ATDD scenarios failed. AssertionError: expected:<2> but was:<11>

### ISSUE THREAD

**Issue by phantomii** [telstra/open-kilda#1031]
git commit: 533aa9eab

how to reproduce:
```
make build-base
make compile
docker-compose build
make up-test-mode
make atdd
```
result:
```
Failed scenarios:
FlowCrudBasicRun.feature:39 # Scenario Outline: Flow Creation on Small Linear Network Topology
TopologyDiscoveryBasic.feature:73 # Scenario: Ignore not signed LLDP packets

42 Scenarios (2 failed, 40 passed)
479 Steps (2 failed, 10 skipped, 467 passed)
33m56.565s

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.openkilda.atdd.FlowCrudBasicRunTest.checkFlowCreation(FlowCrudBasicRunTest.java:115)
	at ✽.Then flow c3none with de:ad:be:ef:00:00:00:03 1 0 and de:ad:be:ef:00:00:00:05 2 0 and 10000 could be created(FlowCrudBasicRun.feature:21)

java.lang.AssertionError: expected:<2> but was:<11>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.openkilda.topo.TestUtils.validateTopos(TestUtils.java:48)
	at org.openkilda.atdd.TopologyDiscoveryBasicTest.the_controller_learns_the_topology(TopologyDiscoveryBasicTest.java:71)
	at ✽.And the controller learns the topology(TopologyDiscoveryBasic.feature:79)

[ERROR] Tests run: 521, Failures: 4, Errors: 0, Skipped: 10, Time elapsed: 2,038.263 s <<< FAILURE! - in org.openkilda.atdd._RunCucumberTest
[ERROR] Then flow c3none with de:ad:be:ef:00:00:00:03 1 0 and de:ad:be:ef:00:00:00:05 2 0 and 10000 could be created(| c3none | de:ad:be:ef:00:00:00:03 | 1 | 0 | de:ad:be:ef:00:00:00:05 | 2 | 0 | 10000 |)  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.AssertionError

[ERROR] | c3none | de:ad:be:ef:00:00:00:03 | 1 | 0 | de:ad:be:ef:00:00:00:05 | 2 | 0 | 10000 |  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.AssertionError

[ERROR] And the controller learns the topology(Scenario: Ignore not signed LLDP packets)  Time elapsed: 0.003 s  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<11>

[ERROR] Scenario: Ignore not signed LLDP packets  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<11>

[INFO] Running org.openkilda.topo.builders.TeTopologyParserTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.openkilda.topo.builders.TeTopologyParserTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   expected:<2> but was:<11>
[ERROR]   expected:<2> but was:<11>
[ERROR] | c3none | de:ad:be:ef:00:00:00:03 | 1 | 0 | de:ad:be:ef:00:00:00:05 | 2 | 0 | 10000 |.Then flow c3none with de:ad:be:ef:00:00:00:03 1 0 and de:ad:be:ef:00:00:00:05 2 0 and 10000 could be created(| c3none | de:ad:be:ef:00:00:00:03 | 1 | 0 | de:ad:be:ef:00:00:00:05 | 2 | 0 | 10000 |)
[ERROR]   Run 1: null
[INFO]   Run 2: PASS
[INFO] 
[ERROR] | c3none | de:ad:be:ef:00:00:00:03 | 1 | 0 | de:ad:be:ef:00:00:00:05 | 2 | 0 | 10000 |.| c3none | de:ad:be:ef:00:00:00:03 | 1 | 0 | de:ad:be:ef:00:00:00:05 | 2 | 0 | 10000 |
[ERROR]   Run 1: null
[INFO]   Run 2: PASS
[INFO] 
[INFO] 
[ERROR] Tests run: 515, Failures: 4, Errors: 0, Skipped: 2
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 34:07 min
[INFO] Finished at: 2018-07-23T15:08:40+03:00
[INFO] Final Memory: 30M/642M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20:test (default-test) on project atdd: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/agent/project/open-kilda/services/src/atdd/target/junit for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Makefile:111: recipe for target 'atdd' failed
make: *** [atdd] Error 1

```

should be:
```
All tests should be passed
```

**Comment by pzakatov** [comment]
@phantomii , why you put this back to Backlog?

**Comment by rtretyak** [comment]
@phantomii is this still relevant?
