### ISSUE TITLE
[WFM] Issue in message deserialisation

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#113]
At least one set of messages lead to unhandled error into "CTRL" code.

```
2017-12-13 12:24:41.787 o.o.w.t.s.StatsTopology [ERROR] Unhandled exception
org.openkilda.wfm.MessageFormatException: Invalid input message/tuple
	at org.openkilda.wfm.protocol.JsonMessage.<init>(JsonMessage.java:28) ~[stormjar.jar:?]
	at org.openkilda.wfm.protocol.KafkaMessage.<init>(KafkaMessage.java:12) ~[stormjar.jar:?]
	at org.openkilda.wfm.topology.event.PopulateIslFilterAction.handle(PopulateIslFilterAction.java:30) ~[stormjar.jar:?]
	at org.openkilda.wfm.AbstractAction.run(AbstractAction.java:25) [stormjar.jar:?]
	at org.openkilda.wfm.topology.event.OFELinkBolt.doWork(OFELinkBolt.java:138) [stormjar.jar:?]
	at org.openkilda.wfm.topology.utils.AbstractTickStatefulBolt.execute(AbstractTickStatefulBolt.java:84) [stormjar.jar:?]
	at org.apache.storm.topology.StatefulBoltExecutor.doExecute(StatefulBoltExecutor.java:145) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.topology.StatefulBoltExecutor.handleTuple(StatefulBoltExecutor.java:137) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.topology.BaseStatefulBoltExecutor.execute(BaseStatefulBoltExecutor.java:78) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.daemon.executor$fn__9866$tuple_action_fn__9868.invoke(executor.clj:730) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.daemon.executor$mk_task_receiver$fn__9787.invoke(executor.clj:462) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.disruptor$clojure_handler$reify__9301.onEvent(disruptor.clj:40) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:472) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:451) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:73) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.daemon.executor$fn__9866$fn__9879$fn__9932.invoke(executor.clj:849) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at org.apache.storm.util$async_loop$fn__555.invoke(util.clj:484) [storm-core-1.1.0.2.6.2.0-205.jar:1.1.0.2.6.2.0-205]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "flowid" (class org.openkilda.messaging.model.ImmutablePair), not marked as ignorable (2 known properties: "reverse", "forward"])
 at [Source: {
    "timestamp": 1513159401394, 
    "correlation_id": "topology_reader-1513159401.39", 
    "destination": "WFM_CACHE", 
    "type": "INFO", 
    "payload": {
        "operation": "CACHE", 
        "message_type": "flow_operation", 
        "payload": {
            "forward": {
                "src_port": 1, 
                "bandwidth": 2000, 
                "flowid": "pre-populated-frw1", 
                "dst_switch": "00:00:00:00:ab:00:00:02", 
                "src_switch": "00:00:00:00:ab:00:00:01", 
                "cookie": 22213, 
                "dst_port": 2, 
                "src_vlan": 0, 
                "dst_vlan": 0
            }, 
            "flowid": "pre-populated-1", 
            "reverse": {}
        }
    }
}; line: 23, column: 10] (through reference chain: org.openkilda.messaging.info.InfoMessage["payload"]->org.openkilda.messaging.info.flow.FlowInfoData["payload"]->org.openkilda.messaging.model.ImmutablePair["flowid"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1478) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1432) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:421) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:183) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:502) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:511) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:400) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1191) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:183) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:1082) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:63) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798) ~[stormjar.jar:?]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2842) ~[stormjar.jar:?]
	at org.openkilda.wfm.protocol.KafkaMessage.unpackJson(KafkaMessage.java:21) ~[stormjar.jar:?]
	at org.openkilda.wfm.protocol.KafkaMessage.unpackJson(KafkaMessage.java:10) ~[stormjar.jar:?]
	at org.openkilda.wfm.protocol.JsonMessage.<init>(JsonMessage.java:26) ~[stormjar.jar:?]
	... 18 more
```

**Comment by surabujin** [comment]
It is not CTRL code it is "port discovery" filter configuration code.
