### ISSUE TITLE
InvalidFormatException Errors in FL log file on atdd

### ISSUE THREAD

**Issue by nikitamarchenko** [telstra/open-kilda#163]
found on 3d0d7855b99150351162d720d7472155ee749adb
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of org.openkilda.messaging.Destination from String value 'org.openkilda.messaging.command.CommandMessage': value not one of declared Enum instance names: [NORTHBOUND, TOPOLOGY_ENGINE, CONTROLLER, WFM, WFM_STATS, WFM_CACHE, WFM_TRANSACTION, WFM_OF_DISCOVERY, WFM_CTRL, CTRL_CLIENT]
 at [Source: {
    "timestamp": 1515520802587, 
    "correlation_id": "1515520802425", 
    "destination": "SPEAKER", 
    "payload": {
        "switch_id": "de:ad:be:ef:00:00:00:02", 
        "clazz": "org.openkilda.messaging.command.flow.RemoveFlow", 
        "flowid": "d3push-1515520547951", 
        "cookie": 2305843009213693953, 
        "meter_id": 0, 
        "transaction_id": 0
    }, 
    "clazz": "org.openkilda.messaging.command.CommandMessage"
}; line: 12, column: 6]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:810)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:127)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:81)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:17)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:344)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:956)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:41)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
	at org.openkilda.floodlight.kafka.KafkaMessageCollector$ParseRecord.parseRecord(KafkaMessageCollector.java:369)
	at org.openkilda.floodlight.kafka.KafkaMessageCollector$ParseRecord.run(KafkaMessageCollector.java:381)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
ATDD tests are green.

**Comment by carmine** [comment]
fixed in PR #166
