### ISSUE TITLE
FL unhandled InvalidFormatException 

### ISSUE THREAD

**Issue by nikitamarchenko** [telstra/open-kilda#180]
found on 49c6a7da5195b191029906ff8843104edf9904aa
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of org.openkilda.messaging.Destination from String value 'org.openkilda.messaging.command.CommandMessage': value not one of declared Enum instance names: [NORTHBOUND, TOPOLOGY_ENGINE, CONTROLLER, WFM, WFM_STATS, WFM_CACHE, WFM_TRANSACTION, WFM_OF_DISCOVERY, WFM_CTRL, CTRL_CLIENT]
 at [Source: {
    "timestamp": 1515781570791, 
    "correlation_id": "RESTORE", 
    "destination": "SPEAKER", 
    "payload": {
        "switch_id": "de:ad:be:ef:00:00:00:01", 
        "clazz": "org.openkilda.messaging.command.flow.RemoveFlow", 
        "flowid": "flow-02", 
        "cookie": 2305843009213693954, 
        "meter_id": 0, 
        "transaction_id": 0
    }, 
    "clazz": "org.openkilda.messaging.command.CommandMessage"
}; line: 12, column: 6]
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:55)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:810)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:127)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:81)
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:17)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:344)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:156)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:956)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:41)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3066)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2161)
	at org.openkilda.floodlight.kafka.KafkaMessageCollector$ParseRecord.parseRecord(KafkaMessageCollector.java:369)
	at org.openkilda.floodlight.kafka.KafkaMessageCollector$ParseRecord.run(KafkaMessageCollector.java:381)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by carmine** [comment]
It seems as though CacheBolt is the only class that uses "RESTORE" as the correlation ID. There was a bug a few commits ago related to using SPEAKER for remove and installs, but this has been removed.

**Comment by carmine** [comment]
Was this from the logfile from Floodlight? I can't reproduce when running `make atdd`

**Comment by nikitamarchenko** [comment]
I just check that bug on 3601f0be528e4ce540cf95f41b8dd65a99650ae1 and I have not reproduce.
