### ISSUE TITLE
Errors with code 500 from topology-engine-rest

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#254]
After converting all neo4j request into py2neo calls TE fails:

```
[pid: 20|app: 0|req: 7/14] 172.19.0.1 () {36 vars in 518 bytes} [Wed Feb  7 16:07:33 2018] GET /api/v1/topology/links => generated 63281 bytes in 162 msecs (HTTP/1.1 200) 2 
headers in 74 bytes (2 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 258, in decorated_view
    return func(*args, **kwargs)
  File "./app/topology.py", line 119, in api_v1_topo_clear
    neo4j_connect.run(query)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 731, in run
    return self.begin(autocommit=True).run(statement, parameters, **kwparameters)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 1277, in run
    self.finish()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 1296, in finish
    self._sync()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 1286, in _sync
    connection.fetch()
  File "/usr/local/lib/python2.7/dist-packages/py2neo/packages/neo4j/v1/bolt.py", line 344, in fetch
    handler(*fields)
  File "/usr/local/lib/python2.7/dist-packages/py2neo/database/__init__.py", line 961, in on_failure
    raise GraphError.hydrate(metadata)
py2neo.database.status.TransientError: LockClient[17652] can't wait on resource RWLock[RELATIONSHIP(780), hash=617755012] since => LockClient[17652] <-[:HELD_BY]- RWLock[REL
ATIONSHIP(794), hash=214482864] <-[:WAITING_FOR]- LockClient[19635] <-[:HELD_BY]- RWLock[RELATIONSHIP(780), hash=617755012]
```

This failures is irregular. "internet" guys believe that this happens due to timeout wile waiting lock on neo4j side.

**Comment by surabujin** [comment]
```
class TransientError(GraphError):
    """ The database cannot service the request right now, retrying later might yield a successful outcome.
    """
```
According to docstring of this error... we should invent retry mechanism and install it around ALL py2neo calls.
