### ISSUE TITLE
FIX NullPointerExceptions into FL

### ISSUE THREAD

**Issue by surabujin** [telstra/open-kilda#288]
FL code produce NPEs in several places. Here is one such place:

```
java.lang.NullPointerException: null
	at org.openkilda.floodlight.switchmanager.SwitchManager.installMeter(SwitchManager.java:472)
	at org.openkilda.floodlight.kafka.RecordHandler.doInstallOneSwitchFlow(RecordHandler.java:220)
	at org.openkilda.floodlight.kafka.RecordHandler.doControllerMsg(RecordHandler.java:72)
	at org.openkilda.floodlight.kafka.RecordHandler.parseRecord(RecordHandler.java:334)
	at org.openkilda.floodlight.kafka.RecordHandler.run(RecordHandler.java:342)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

The root cause of this issue - is use result of IOFSwitchService.getSwitch call without check for null value. This method return null values if there is no switch with requested dpId.

There is a lot of calls to this method without check for null response into org.openkilda.floodlight.switchmanager.SwitchManager

**Comment by surabujin** [comment]
@carmine this ticket can be closed, because https://github.com/telstra/open-kilda/pull/289 have been merged already
