### ISSUE TITLE
can't enable protected path on a flow via v2 immediatly after updating multiTable mode in switch properties

### ISSUE THREAD

**Issue by andriidovhan** [telstra/open-kilda#3034]
**Steps to reproduce**
run test: `def "Flow rules are not reinstalled according to switch property while swapping to protected path"()`

please remove `sleep` before running test 
```
and: "Update switch properties(multi_table: false) on the dst switch"
        northbound.updateSwitchProperties(involvedSwitches[2].dpId,
                changeSwitchPropsMultiTableValue(initSwProps[involvedSwitches[2].dpId], false))
        sleep(3000) // <= SHOULD BE DELETED

and: "Enable protected path on the flow"
        northboundV2.updateFlow(flow.flowId, flow.tap { it.allocateProtectedPath = true })
        Wrappers.wait(WAIT_OFFSET, 1) {
            with(northbound.getFlow(flow.flowId).flowStatusDetails) {
                mainFlowPathStatus == "Up"
                protectedFlowPathStatus == "Up"
            }
        }
```

**Actual result**
Protected path is not enabled.
Rule validation is failed during updating.
```
Command <egress-flow-segment-VERIFY{id=f5f0ee45-1cbf-11ea-8369-55a1b068b218, metadata=FlowSegmentMetadata(flowId=12Dec111536_331_creamcheese9075, cookie=0x4000000000000002, multiTable=false), endpoint=FlowEndpoint(super=NetworkEndpoint(switchId=00:00:00:00:00:00:00:02, portNumber=16), vlanId=1394, trackConnectedDevices=false), ingressEndpoint=FlowEndpoint(super=NetworkEndpoint(switchId=00:00:00:00:00:00:00:08, portNumber=10), vlanId=137, trackConnectedDevices=false), isl_port=1, encapsulation=FlowTransitEncapsulation(id=3, type=TRANSIT_VLAN)}> on 00:00:00:00:00:00:00:02 have failed with error: org.openkilda.floodlight.error.SwitchMissingFlowsException: Detect 1 missing OF flows on 00:00:00:00:00:00:00:02 related to flow 12Dec111536_331_creamcheese9075 cookie 0x4000000000000002 (total verified 1 OF messages) (exec time: PT0S)
```

```
org.openkilda.floodlight.error.SwitchMissingFlowsException: Detect 1 missing OF flows on 00:00:00:00:00:00:00:02 related to flow 12Dec111536_331_creamcheese9075 cookie 0x4000000000000002 (total verified 1 OF messages)
	at org.openkilda.floodlight.command.flow.FlowSegmentCommand.handleVerifyResponse(FlowSegmentCommand.java:90)
	at org.openkilda.floodlight.command.flow.FlowSegmentCommand.lambda$makeVerifyPlan$0(FlowSegmentCommand.java:71)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.openkilda.floodlight.utils.OfFlowPresenceVerifier.handleComplete(OfFlowPresenceVerifier.java:97)
	at org.openkilda.floodlight.utils.OfFlowPresenceVerifier.lambda$new$1(OfFlowPresenceVerifier.java:75)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:736)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at org.openkilda.floodlight.utils.CompletableFutureAdapter$1.onSuccess(CompletableFutureAdapter.java:38)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1773)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:456)
	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:817)
	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:753)
	at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:613)
	at net.floodlightcontroller.core.DeliverableListenableFuture.deliver(DeliverableListenableFuture.java:24)
	at net.floodlightcontroller.core.internal.OFConnection$1.deliver(OFConnection.java:221)
	at net.floodlightcontroller.core.internal.OFConnection$1.deliver(OFConnection.java:212)
	at net.floodlightcontroller.core.internal.OFConnection.handleGenericDeliverable(OFConnection.java:300)
	at net.floodlightcontroller.core.internal.OFConnection.deliverResponse(OFConnection.java:343)
	at net.floodlightcontroller.core.internal.OFConnection.messageReceived(OFConnection.java:413)
	at net.floodlightcontroller.core.internal.OFChannelHandler.sendMessageToConnection(OFChannelHandler.java:579)
	at net.floodlightcontroller.core.internal.OFChannelHandler.access$800(OFChannelHandler.java:57)
	at net.floodlightcontroller.core.internal.OFChannelHandler$OFChannelState.processOFMessage(OFChannelHandler.java:284)
	at net.floodlightcontroller.core.internal.OFChannelHandler.channelRead0(OFChannelHandler.java:698)
	at net.floodlightcontroller.core.internal.OFChannelHandler.channelRead0(OFChannelHandler.java:57)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:748)
```
**Expected result**
protectedPath should be enabled

**NOTE:**
it works fine via APIv1

**Comment by rtretyak** [comment]
This may not be limited only by update operation. I observe the same unpredictable behavior when doing path swap on a protected flow right after change table mode on the switch

**Comment by niksv** [comment]
Won't fix because single table mode is [deprecated](https://github.com/telstra/open-kilda#deprecation)
