### ISSUE TITLE
ATDD failure on one Update scenario

### ISSUE THREAD

**Issue by carmine** [telstra/open-kilda#316]
Failed scenarios:
FlowCrudBasicRun.feature:171 # Scenario Outline: Flow Updating on Small Linear Network Topology

34 Scenarios (1 failed, 33 passed)
354 Steps (1 failed, 6 skipped, 347 passed)
18m18.067s

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at org.junit.Assert.assertNotNull(Assert.java:722)
	at org.openkilda.atdd.FlowCrudBasicRunTest.successfulFlowCreation(FlowCrudBasicRunTest.java:72)
	at ✽.When flow u3push creation request with de:ad:be:ef:00:00:00:03 1 0 and de:ad:be:ef:00:00:00:05 2 100 and 10000 is successful(FlowCrudBasicRun.feature:158)

**Comment by jac0by** [comment]
The updated create_flow relies on segment_latency supplied with each segment of a path, and according to the code the segment_latency is read from ISL relations in Neo4J. But the issue represents a situation when ISLs don't have latency set in the moment when we attempt to create a flow (probably because the discovery processes are not finished yet).
