### ISSUE TITLE
Functional tests ignores no_floodlight_2: true in docker-compose.yaml

### ISSUE THREAD

**Issue by nikitamarchenko** [telstra/open-kilda#4033]
Functional tests ignores no_floodlight_2: true in docker-compose.yaml.

Step to reproduce:
- set no_floodlight_2: true in docker-compose.yaml
- run make func-tests
- seen an error "Exception: Couldn't resolve host 'floodlight_2.pendev', seems like Floodlight is down"

```
org.openkilda.functionaltests.spec.resilience.StormHeavyLoadSpec > Spring context is set UP FAILED
    java.lang.IllegalStateException: Failed to load ApplicationContext
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
        at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
        at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:117)
        at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:83)
        at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:246)
        at org.spockframework.spring.SpringTestContextManager.prepareTestInstance(SpringTestContextManager.java:56)
        at org.spockframework.spring.SpringInterceptor.interceptInitializerMethod(SpringInterceptor.java:43)
        at org.spockframework.runtime.extension.AbstractMethodInterceptor.intercept(AbstractMethodInterceptor.java:24)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:98)
        at org.openkilda.functionaltests.extension.failfast.FailFastExtension$1.intercept(FailFastExtension.groovy:24)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
        at org.openkilda.functionaltests.extension.env.AssumeProfileExtension$1.intercept(AssumeProfileExtension.groovy:32)
        at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:97)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

        Caused by:
        org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationContextProvider' defined in class path resource [spring-context.xml]: Initialization of bean failed; nested exception is org.springframework.web.client.HttpServerErrorException: 500 INTERNAL SERVER ERROR
        Traceback (most recent call last):
          File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 36, in resolve_host
            ip = socket.gethostbyname(parts[1])
        socket.gaierror: [Errno -2] Name or service not known

        The above exception was the direct cause of the following exception:

        Traceback (most recent call last):
          File "/usr/local/lib/python3.8/dist-packages/service/service.py", line 43, in main
            topo = Topology.create(topo_def)
          File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 246, in create
            sw = Switch.create_with_ports(sw_def)
          File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 77, in create_with_ports
            sw = Switch.create(sw_def)
          File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 61, in create
            controller = " ".join([resolve_host(cnt) for cnt in sw_def['controller'].split(" ")])
          File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 61, in <listcomp>
            controller = " ".join([resolve_host(cnt) for cnt in sw_def['controller'].split(" ")])
          File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 38, in resolve_host
            raise Exception("Couldn't resolve host '%s', seems like Floodlight is down" % parts[1]) from e  # noqa
        Exception: Couldn't resolve host 'floodlight_2.pendev', seems like Floodlight is down
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:589)
            at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503)
            at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
            at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
            at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
            at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
            at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
            at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
            at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
            at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:128)
            at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:60)
            at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:107)
            at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
            at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
            at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
            ... 34 more

            Caused by:
            org.springframework.web.client.HttpServerErrorException: 500 INTERNAL SERVER ERROR
            Traceback (most recent call last):
              File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 36, in resolve_host
                ip = socket.gethostbyname(parts[1])
            socket.gaierror: [Errno -2] Name or service not known

            The above exception was the direct cause of the following exception:

            Traceback (most recent call last):
              File "/usr/local/lib/python3.8/dist-packages/service/service.py", line 43, in main
                topo = Topology.create(topo_def)
              File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 246, in create
                sw = Switch.create_with_ports(sw_def)
              File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 77, in create_with_ports
                sw = Switch.create(sw_def)
              File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 61, in create
                controller = " ".join([resolve_host(cnt) for cnt in sw_def['controller'].split(" ")])
              File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 61, in <listcomp>
                controller = " ".join([resolve_host(cnt) for cnt in sw_def['controller'].split(" ")])
              File "/usr/local/lib/python3.8/dist-packages/service/topology.py", line 38, in resolve_host
                raise Exception("Couldn't resolve host '%s', seems like Floodlight is down" % parts[1]) from e  # noqa
            Exception: Couldn't resolve host 'floodlight_2.pendev', seems like Floodlight is down
                at org.openkilda.testing.tools.ExtendedErrorHandler.handleError(ExtendedErrorHandler.java:48)
                at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
                at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:766)
                at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:724)
                at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:680)
                at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:600)
                at org.openkilda.testing.service.labservice.LabServiceImpl.createLab(LabServiceImpl.java:64)
                at org.openkilda.functionaltests.extension.env.EnvExtension.buildVirtualEnvironment(EnvExtension.groovy:120)
                at org.openkilda.functionaltests.extension.env.EnvExtension.notifyContextInitialized(EnvExtension.groovy:70)
                at org.openkilda.functionaltests.extension.spring.SpringContextExtension.setApplicationContext_closure2(SpringContextExtension.groovy:61)
                at groovy.lang.Closure.call(Closure.java:405)
                at groovy.lang.Closure.call(Closure.java:421)
                at org.openkilda.functionaltests.extension.spring.SpringContextExtension.setApplicationContext(SpringContextExtension.groovy:60)
                at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:120)
                at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:96)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:424)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700)
                at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581)
                ... 48 more
```

**Comment by nikitamarchenko** [comment]
The same with floodlight_stats

**Comment by rtretyak** [comment]
We should also think of how to automatically understand when other components are excluded from the build (e.g. grpc service) and adjust test suite accordingly
