### ISSUE TITLE
Implement checks for PathVerificationService#handlePacketIn

### ISSUE THREAD

**Issue by nikitamarchenko** [telstra/open-kilda#65]
Step to reproduce
1. Create simple topology
2. Run code in scapy
```
$ docker exec -ti mininet scapy
Welcome to Scapy (2.2.0)
>>> sendp(Ether(dst="00:26:e1:ff:ff:ff")/ IP(dst="192.168.0.255")/UDP(dport=61231,sport=61231)/'\0x01\0xFF\x00\x00', iface="00000001-eth1")
.
Sent 1 packets.
```
In `docker logs -f openkilda_floodlight_1 ` you can see 
```
2017-11-13 16:37:24.434 ERROR [o.o.f.p.PathVerificationService] unknown error during packet_in message processing: null
java.lang.NullPointerException: null
	at org.openkilda.floodlight.pathverification.PathVerificationService.handlePacketIn(PathVerificationService.java:423) [floodlight-modules.jar:na]
	at org.openkilda.floodlight.pathverification.PathVerificationService.receive(PathVerificationService.java:207) [floodlight-modules.jar:na]
	at net.floodlightcontroller.core.internal.Controller.handleMessage(Controller.java:407) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFSwitchManager.handleMessage(OFSwitchManager.java:487) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler.dispatchMessage(OFSwitchHandshakeHandler.java:1752) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler.access$2000(OFSwitchHandshakeHandler.java:95) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler$MasterState.processOFPacketIn(OFSwitchHandshakeHandler.java:1488) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler$OFSwitchHandshakeState.processOFMessage(OFSwitchHandshakeHandler.java:839) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler.processOFMessage(OFSwitchHandshakeHandler.java:1790) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFSwitchHandshakeHandler.messageReceived(OFSwitchHandshakeHandler.java:1964) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFConnection.messageReceived(OFConnection.java:414) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFChannelHandler.sendMessageToConnection(OFChannelHandler.java:579) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFChannelHandler.access$800(OFChannelHandler.java:57) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFChannelHandler$OFChannelState.processOFMessage(OFChannelHandler.java:284) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFChannelHandler.channelRead0(OFChannelHandler.java:696) [floodlight.jar:1.2-SNAPSHOT]
	at net.floodlightcontroller.core.internal.OFChannelHandler.channelRead0(OFChannelHandler.java:57) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [floodlight.jar:1.2-SNAPSHOT]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [floodlight.jar:1.2-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```
Need to write code for avoiding malformed packets.

**Comment by pzakatov** [comment]
@nikitamarchenko , review details

**Comment by pzakatov** [comment]
outdated
