### ISSUE TITLE
deleteRules for invalid switchId causes unhandled exception

### ISSUE THREAD

**Issue by sergii-iakovenko** [telstra/open-kilda#950]
Processing of deleteRules for a missing switch causes "unhandled exception" message being logged in FL:
```
java.lang.IllegalArgumentException: Switch de:ad:be:ef:00:00:00:00 was not found
	at org.openkilda.floodlight.switchmanager.SwitchManager.dumpFlowTable(SwitchManager.java:468)
	at org.openkilda.floodlight.switchmanager.SwitchManager.deleteRulesByCriteria(SwitchManager.java:648)
	at org.openkilda.floodlight.kafka.RecordHandler.doDeleteFlow(RecordHandler.java:371)
	at org.openkilda.floodlight.kafka.RecordHandler.handleCommand(RecordHandler.java:138)
	at org.openkilda.floodlight.kafka.RecordHandler.doControllerMsg(RecordHandler.java:112)
	at org.openkilda.floodlight.kafka.RecordHandler.parseRecord(RecordHandler.java:680)
	at org.openkilda.floodlight.kafka.RecordHandler.run(RecordHandler.java:688)
```

**Expected Results** 
Floodlight module responds with ErrorMessage and corresponding details.

**Comment by abochkarev** [comment]
@sergii-iakovenko Could you please add more information about expected results? Am I correct that we need to return the error response?

**Comment by sergii-iakovenko** [comment]
FL should send an ErrorMessage as the response on unprocessable SwitchRulesDeleteRequest. And in the case of missing switch, NB should return 404 response code with corresponding description (Switch de:ad:be:ef:00:00:00:00 was not found).
